name: Build with Nuitka

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install nuitka
        pip install -r metro_time_requirements.txt
    
    - name: Build
      run: |
        python -m nuitka `
          --standalone `
          --windows-console-mode=disable `
          --include-data-files=time.png=time.png `
          --windows-icon-from-ico=time.ico `
          --output-filename=时刻表助手 `
          --jobs=2 `
          --assume-yes-for-downloads `
          --enable-plugin=pyqt6 `
          metro_time.py
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: 时刻表助手
        path: metro_time.dist/
